name: deploy-website

on:
  push:
    branches:
    - main

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Install MyST MD
      run: npm install -g mystmd

    - name: Build the site
      run: myst build --html

    - name: Add custom domain
      run: echo "sgsa.berkeley.edu" > ./_build/html/CNAME

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
